#!/usr/bin/env python3
"""spec-graph check #7 — null-stub discrimination, mechanized (the phase-F kill for
vacuous greens).

Write a throwaway no-op implementation of the target, run the suite against it once:
every test must fail, each on its own demand-specific assertion. A test green against a
do-nothing implementation binds nothing; a test that errors instead of asserting is
riding a sibling's machinery. This script does the mechanical part — generate the stub,
run pytest, classify per test — and leaves the judgment (is a recorded pass legitimate?
is a rider repairable?) to the phase-F leaf.

Mechanics:

* **Target** — `_suite.target_modules` (the suite's unresolvable project-rooted
  imports), plus `--target <dotted.module>` for the modify-existing case. Each target
  becomes a module in a temp directory whose every attribute is a `_Null` object:
  callable (returns itself), attribute-transparent, falsy, empty, equal to nothing —
  so tests reach their own assertions instead of dying on `None` plumbing.
* **Run** — `<python> -m pytest <suite-dir> -p nullstub_report`, with the stub dir
  prepended to `PYTHONPATH` and cwd at the suite's nearest pyproject/pytest.ini ancestor
  (the project's own pytest config must apply). The interpreter must be the project's
  test interpreter: `--python`, else `$SPEC_GRAPH_TEST_PYTHON`, else `python3`.
* **Classify** — per test: `failed on AssertionError` is discrimination; `passed` is a
  finding unless the graph's `handoff.nullstub_passes` records it; an error, skip, or
  collection failure proves nothing and is a finding.

The stub lives in a temp directory and is deleted after the run (`--keep` to inspect) —
committing it would hand write-code-from-spec a skeleton to grow instead of a contract
to meet. Namespace-package caveat: a stub submodule can only merge into a package that
is itself a namespace package; if a regular (`__init__.py`) ancestor shadows it, the run
warns and the import will fail loudly rather than silently testing real code.

Usage:
    spec-graph nullstub [graph.yaml | suite-dir] [--target <dotted.module> ...]
                        [--python <interp>] [--keep] [--config <path>]
Exit codes: 0 every test discriminates (or its pass is recorded); 1 findings; 2 the
run could not happen (no target, no pytest, no report) — never a silent pass.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

import _config
import _suite

_NULL_MODULE = '''\
"""Null-stub target module — generated by `spec-graph nullstub`, NEVER committed."""


class _Null:
    def __call__(self, *a, **k):
        return self

    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"):
            raise AttributeError(name)  # stay honest with protocol probes (copy, pickle, …)
        return self

    def __iter__(self):
        return iter(())

    def __bool__(self):
        return False

    def __len__(self):
        return 0

    def __eq__(self, other):
        return other is self

    def __ne__(self, other):
        return other is not self

    __hash__ = object.__hash__

    def __repr__(self):
        return "<nullstub>"


def __getattr__(name):
    return _Null()
'''

_PLUGIN = '''\
"""pytest plugin: record per-test outcome + crash line for the null-stub classifier."""
import json
import os

_R = {}


def pytest_runtest_logreport(report):
    entry = _R.setdefault(report.nodeid, {})
    if report.skipped:
        entry["outcome"] = "skipped"
    elif report.failed:
        crash = getattr(getattr(report, "longrepr", None), "reprcrash", None)
        msg = getattr(crash, "message", None) or str(report.longrepr or "")
        entry["outcome"] = "failed" if report.when == "call" else "error-" + report.when
        entry["message"] = msg.splitlines()[0][:200] if msg else ""
    elif report.when == "call" and "outcome" not in entry:
        entry["outcome"] = "passed"


def pytest_collectreport(report):
    if report.failed:
        _R[str(report.nodeid) or "<collection>"] = {
            "outcome": "collection-error", "message": str(report.longrepr)[:400]}


def pytest_sessionfinish(session, exitstatus):
    path = os.environ.get("NULLSTUB_REPORT_FILE")
    if path:
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(_R, fh)
'''


def _write_stub(stub_dir: Path, targets: dict[str, set[str]], root: Path) -> None:
    for dotted in targets:
        parts = dotted.split(".")
        mod = stub_dir.joinpath(*parts).with_suffix(".py")
        mod.parent.mkdir(parents=True, exist_ok=True)
        mod.write_text(_NULL_MODULE, encoding="utf-8")
        for depth in range(1, len(parts)):
            if (root.joinpath(*parts[:depth]) / "__init__.py").is_file():
                print(
                    f"  WARN [check_stub] {'.'.join(parts[:depth])} is a regular package "
                    f"(__init__.py) — the stub for {dotted} cannot merge into it and the "
                    f"import will fail as a collection error, not silently test real code.",
                    file=sys.stderr,
                )


def _pytest_cwd(suite_dir: Path, root: Path) -> Path:
    d = suite_dir
    while d != root.parent:
        if any((d / f).is_file() for f in ("pyproject.toml", "pytest.ini", "setup.cfg", "tox.ini")):
            return d
        if d == root:
            break
        d = d.parent
    return root


def _recorded_passes(suite_dir: Path) -> set[str]:
    """Test names listed in any sibling graph's handoff.nullstub_passes ("<test> — <class>")."""
    recorded: set[str] = set()
    for g in sorted(suite_dir.glob("spec_graph_*.yaml")):
        try:
            handoff = (yaml.safe_load(g.read_text(encoding="utf-8")) or {}).get("handoff") or {}
        except yaml.YAMLError:
            continue
        for entry in handoff.get("nullstub_passes", []) or []:
            recorded.add(str(entry).split("—")[0].split("--")[0].strip())
    return recorded


def run(suite_dir: Path, targets: dict[str, set[str]], python: str, keep: bool) -> int:
    root = _config.repo_root()
    stub_dir = Path(tempfile.mkdtemp(prefix="nullstub-"))
    report_file = stub_dir / "report.json"
    try:
        _write_stub(stub_dir, targets, root)
        (stub_dir / "nullstub_report.py").write_text(_PLUGIN, encoding="utf-8")
        env = dict(os.environ)
        env["PYTHONPATH"] = os.pathsep.join(
            [str(stub_dir), env.get("PYTHONPATH", "")]).rstrip(os.pathsep)
        env["NULLSTUB_REPORT_FILE"] = str(report_file)
        cmd = [python, "-m", "pytest", str(suite_dir), "-q", "--no-header",
               "-p", "nullstub_report"]
        proc = subprocess.run(
            cmd, cwd=_pytest_cwd(suite_dir, root), env=env,
            capture_output=True, text=True, encoding="utf-8", timeout=600,
        )
        if not report_file.is_file():
            print(f"check_stub: pytest produced no report — the run itself broke:\n"
                  f"{proc.stdout[-2000:]}\n{proc.stderr[-2000:]}", file=sys.stderr)
            return 2
        results: dict[str, dict] = json.loads(report_file.read_text(encoding="utf-8"))
    except subprocess.TimeoutExpired:
        print("check_stub: pytest timed out after 600s against the stub", file=sys.stderr)
        return 2
    finally:
        if keep:
            print(f"  [check_stub] stub kept at {stub_dir} — delete it; it is never committed.",
                  file=sys.stderr)
        else:
            shutil.rmtree(stub_dir, ignore_errors=True)

    recorded = _recorded_passes(suite_dir)
    findings: list[str] = []
    discriminated = 0
    for nodeid, r in sorted(results.items()):
        outcome, msg = r.get("outcome"), r.get("message", "")
        test = nodeid.split("::")[-1]
        if outcome == "failed" and (msg.startswith("AssertionError") or msg.startswith("Failed")):
            discriminated += 1
        elif outcome == "passed":
            if test in recorded:
                discriminated += 1  # an examined pass — recorded with its class in the graph
            else:
                findings.append(
                    f"NULLSTUB-PASS {nodeid}: green against a do-nothing target — binds nothing. "
                    f"Strengthen it, or record it with its class in handoff.nullstub_passes."
                )
        elif outcome == "failed":
            findings.append(
                f"NON-ASSERT {nodeid}: fails on `{msg}`, not its own assertion — it rides "
                f"machinery, so it may stay green when only the demand breaks."
            )
        elif outcome == "skipped":
            findings.append(f"SKIPPED {nodeid}: a skipped test discriminates nothing at spec time.")
        else:
            findings.append(
                f"BROKEN {nodeid}: {outcome} (`{msg}`) — proves the file is broken, not that "
                f"the test discriminates."
            )
    for f in findings:
        print(f"  {f}")
    print(f"\n[check_stub] {discriminated} discriminating, {len(findings)} finding(s), "
          f"targets: {sorted(targets)}.")
    return 1 if findings else 0


def main(argv: list[str]) -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")
    config: str | None = None
    python = os.environ.get("SPEC_GRAPH_TEST_PYTHON", "python3")
    explicit: list[str] = []
    keep = False
    args: list[str] = []
    it = iter(argv)
    for a in it:
        if a == "--config":
            config = next(it, None)
        elif a == "--target":
            t = next(it, None)
            if t:
                explicit.append(t)
        elif a == "--python":
            python = next(it, python)
        elif a == "--keep":
            keep = True
        else:
            args.append(a)
    cfg = _config.load(config)
    root = _config.repo_root()
    if args:
        p = Path(args[0])
        suite_dir = p if p.is_dir() else p.parent
    else:
        dirs = sorted({g.parent for g in _config.artifacts(cfg)})
        if len(dirs) != 1:
            print(f"check_stub: give the suite dir or graph explicitly (found {len(dirs)} "
                  f"candidate dirs)", file=sys.stderr)
            return 2
        suite_dir = dirs[0]
    targets, floor = _suite.target_modules(suite_dir, root)
    for t in explicit:
        targets.setdefault(t, set())
    for note in floor:
        print(f"  WARN [check_stub] {note}", file=sys.stderr)
    if not targets:
        print(
            f"check_stub: no target identified for {suite_dir} — every suite import resolves. "
            f"Name the modify-case target with --target <dotted.module>.",
            file=sys.stderr,
        )
        return 2
    return run(suite_dir, targets, python, keep)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
