#!/usr/bin/env python3
"""spec-graph check #7 — null-stub discrimination, mechanized (the phase-F kill for
vacuous greens).

Write a throwaway no-op implementation of the target, run the suite against it once:
every test must fail, each on its own demand-specific assertion. A test green against a
do-nothing implementation binds nothing; a test that errors instead of asserting is
riding a sibling's machinery. This script does the mechanical part — generate the stub,
run pytest, classify per test — and leaves the judgment (is a recorded pass legitimate?
is a rider repairable?) to the phase-F leaf.

Mechanics:

* **Target** — `_suite.target_modules` (the suite's unresolvable project-rooted
  imports), plus `--target <dotted.module>` for the modify-existing case. Each target
  becomes a module in a temp directory whose every attribute is a `_Null` object:
  callable (returns itself), attribute-transparent, falsy, empty, equal to nothing —
  so tests reach their own assertions instead of dying on `None` plumbing.
* **Run** — `<python> -m pytest <suite-dir> -p nullstub_report`, with the stub dir
  prepended to `PYTHONPATH` and cwd at the suite's nearest pyproject/pytest.ini ancestor
  (the project's own pytest config must apply). The interpreter must be the project's
  test interpreter: `--python`, else `$SPEC_GRAPH_TEST_PYTHON`, else `python3`.
* **Classify** — per test: `failed on AssertionError` is discrimination; `passed` is a
  finding unless the graph's `handoff.nullstub_passes` records it; an error, skip, or
  collection failure proves nothing and is a finding.

The stub lives in a temp directory and is deleted after the run (`--keep` to inspect) —
committing it would hand write-code-from-spec a skeleton to grow instead of a contract
to meet. Namespace-package caveat: a stub submodule can only merge into a package that
is itself a namespace package; if a regular (`__init__.py`) ancestor shadows it, the run
warns and the import will fail loudly rather than silently testing real code.

Usage:
    spec-graph nullstub [graph.yaml | suite-dir] [--target <dotted.module> ...]
                        [--python <interp>] [--keep] [--config <path>]
Exit codes: 0 every test discriminates (or its pass is recorded); 1 findings; 2 the
run could not happen (no target, no pytest, no report) — never a silent pass.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

import _cli
import _config
import _suite

_NULL_MODULE = '''\
"""Null-stub target module — generated by `spec-graph nullstub`, NEVER committed."""


class _Null:
    def __call__(self, *a, **k):
        return self

    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"):
            raise AttributeError(name)  # stay honest with protocol probes (copy, pickle, …)
        return self

    def __iter__(self):
        return iter(())

    def __bool__(self):
        return False

    def __len__(self):
        return 0

    # Container/context/ordering plumbing must hand control to the test's own assert;
    # a TypeError raised here (implicit __getattr__ never serves dunders) misclassifies
    # a discriminating test as NON-ASSERT. All answers stay consistent with "empty,
    # falsy, equal to nothing": contains nothing, orders below nothing.
    def __getitem__(self, key):
        return self

    def __contains__(self, item):
        return False

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False  # never swallow — an exception inside `with` must stay visible

    def __lt__(self, other):
        return False

    __le__ = __gt__ = __ge__ = __lt__

    def __eq__(self, other):
        return other is self

    def __ne__(self, other):
        return other is not self

    __hash__ = object.__hash__

    def __repr__(self):
        return "<nullstub>"


def __getattr__(name):
    return _Null()
'''

_PLUGIN = '''\
"""pytest plugin: record per-test outcome + crash line for the null-stub classifier."""
import json
import os
import sys

_R = {}


def pytest_runtest_logreport(report):
    entry = _R.setdefault(report.nodeid, {})
    # A non-call phase must never overwrite what the call phase already proved. Against a
    # null stub, teardown breakage is COMMON (a fixture cleaning up a path the stub never
    # made): overwriting would report a call-phase assertion failure — textbook
    # discrimination — as BROKEN, and a call-phase PASS (the NULLSTUB-PASS finding this
    # check exists for) as BROKEN too. Setup errors with no call outcome still record.
    if report.when != "call" and entry.get("phase") == "call":
        return
    if report.skipped:
        entry["outcome"] = "skipped"
        entry["phase"] = report.when
    elif report.failed:
        crash = getattr(getattr(report, "longrepr", None), "reprcrash", None)
        msg = getattr(crash, "message", None) or str(report.longrepr or "")
        entry["outcome"] = "failed" if report.when == "call" else "error-" + report.when
        entry["message"] = msg.splitlines()[0][:200] if msg else ""
        entry["phase"] = report.when
    elif report.when == "call" and "outcome" not in entry:
        entry["outcome"] = "passed"
        entry["phase"] = "call"


def pytest_collectreport(report):
    if report.failed:
        _R[str(report.nodeid) or "<collection>"] = {
            "outcome": "collection-error", "message": str(report.longrepr)[:400]}
    elif report.skipped:
        # A module skipped at collection (pytest.importorskip, module-level skip) emits no
        # per-test reports at all — unrecorded, the file vanishes from the report and a
        # run of only-skipped modules exits 0, certifying tests that never ran.
        _R[str(report.nodeid) or "<collection>"] = {
            "outcome": "collection-skipped", "message": str(report.longrepr)[:400]}


def pytest_sessionfinish(session, exitstatus):
    # Where each target ACTUALLY imported from. `python -m pytest` puts the cwd ahead of
    # PYTHONPATH, so a target that exists on disk (modify-existing case) can shadow the
    # stub and every verdict silently measures real code; the classifier voids the run
    # when an origin falls outside the stub dir. A target absent from sys.modules is
    # fine — nothing imported it.
    origins = {}
    for t in filter(None, os.environ.get("NULLSTUB_TARGETS", "").split(",")):
        f = getattr(sys.modules.get(t), "__file__", None)
        if f:
            origins[t] = f
    path = os.environ.get("NULLSTUB_REPORT_FILE")
    if path:
        with open(path, "w", encoding="utf-8") as fh:
            json.dump({"results": _R, "origins": origins}, fh)
'''


def _write_stub(stub_dir: Path, targets: dict[str, set[str]], root: Path) -> None:
    for dotted in targets:
        parts = dotted.split(".")
        if any(other.startswith(dotted + ".") for other in targets):
            # A dotted ancestor of another target must be a PACKAGE: a pkg/mod.py file
            # would shadow pkg/mod/, and the child target's import would die as a
            # collection error blamed on the suite.
            mod = stub_dir.joinpath(*parts) / "__init__.py"
        else:
            mod = stub_dir.joinpath(*parts).with_suffix(".py")
        mod.parent.mkdir(parents=True, exist_ok=True)
        mod.write_text(_NULL_MODULE, encoding="utf-8")
        for depth in range(1, len(parts)):
            if (root.joinpath(*parts[:depth]) / "__init__.py").is_file():
                print(
                    f"  WARN [check_stub] {'.'.join(parts[:depth])} is a regular package "
                    f"(__init__.py) — the stub for {dotted} cannot merge into it and the "
                    f"import will fail as a collection error, not silently test real code.",
                    file=sys.stderr,
                )


# Shared config files count as pytest config only WITH their pytest section (pytest's own
# rootdir rules); pytest.ini counts by existence alone.
_PYTEST_SECTIONS = {
    "pyproject.toml": "[tool.pytest.ini_options]",
    "setup.cfg": "[tool:pytest]",
    "tox.ini": "[pytest]",
}


def _has_pytest_config(d: Path) -> bool:
    # A packaging-only setup.cfg (or plain pyproject.toml) in a subdir must not hijack
    # the cwd away from the project's real pytest config. The substring match mirrors
    # pytest's "does the section exist" rule closely enough: a commented-out section is
    # the only false positive, and it costs a plausible-but-different cwd, not a verdict.
    if (d / "pytest.ini").is_file():
        return True
    for name, section in _PYTEST_SECTIONS.items():
        f = d / name
        try:
            if f.is_file() and section in f.read_text(encoding="utf-8"):
                return True
        except OSError:
            continue
    return False


def _pytest_cwd(suite_dir: Path, root: Path) -> Path:
    # Walk `parents`, not a hand-rolled `d = d.parent` loop: at the filesystem root
    # `Path("/").parent` is `/` again, so a suite_dir OUTSIDE the repo tree never reached
    # either guard (`d == root` never true, `d != root.parent` never false) and spun forever.
    # `parents` is finite whatever the two paths' relationship.
    for d in (suite_dir, *suite_dir.parents):
        if _has_pytest_config(d):
            return d
        if d == root:
            break
    return root


def _recorded_passes(suite_dir: Path) -> set[str]:
    """Test names listed in any sibling graph's handoff.nullstub_passes ("<test> — <class>")."""
    recorded: set[str] = set()
    for g in sorted(suite_dir.glob("spec_graph_*.yaml")):
        # A malformed sibling graph must not kill the stub run — skip it; its shape is
        # check_lint's finding, not this check's.
        try:
            handoff = _cli.load_graph(g).get("handoff") or {}
        except (yaml.YAMLError, TypeError):
            continue
        for entry in handoff.get("nullstub_passes", []) or []:
            # The documented separator is the em-dash ONLY; also splitting on "--"
            # truncated legitimate ids (test_flag[--residue] → "test_flag[").
            recorded.add(str(entry).split("—", 1)[0].strip())
    return recorded


def run(suite_dir: Path, targets: dict[str, set[str]], python: str, keep: bool) -> int:
    root = _config.repo_root(suite_dir)
    # resolve(): the shadow check compares module __file__ origins against this dir.
    stub_dir = Path(tempfile.mkdtemp(prefix="nullstub-")).resolve()
    report_file = stub_dir / "report.json"
    try:
        _write_stub(stub_dir, targets, root)
        (stub_dir / "nullstub_report.py").write_text(_PLUGIN, encoding="utf-8")
        env = dict(os.environ)
        env["PYTHONPATH"] = os.pathsep.join(
            [str(stub_dir), env.get("PYTHONPATH", "")]).rstrip(os.pathsep)
        env["NULLSTUB_REPORT_FILE"] = str(report_file)
        env["NULLSTUB_TARGETS"] = ",".join(sorted(targets))
        cmd = [python, "-m", "pytest", str(suite_dir), "-q", "--no-header",
               "-p", "nullstub_report"]
        proc = subprocess.run(
            cmd, cwd=_pytest_cwd(suite_dir, root), env=env,
            capture_output=True, text=True, encoding="utf-8", timeout=600,
        )
        if not report_file.is_file():
            print(f"check_stub: pytest produced no report — the run itself broke:\n"
                  f"{proc.stdout[-2000:]}\n{proc.stderr[-2000:]}", file=sys.stderr)
            return 2
        payload: dict = json.loads(report_file.read_text(encoding="utf-8"))
        results: dict[str, dict] = payload.get("results", {})
        if not results:
            # An empty report is "nothing ran", never "everything discriminated": a suite that
            # silently stopped collecting (renamed files, a conftest that imports but registers
            # nothing) would otherwise certify clean — the one outcome this check exists to deny.
            print(f"check_stub: pytest collected no tests under {suite_dir} — the run proves "
                  f"nothing about discrimination.\n{proc.stdout[-2000:]}", file=sys.stderr)
            return 2
        # `python -m pytest` puts the cwd ahead of PYTHONPATH, so a target that EXISTS on
        # disk (the modify-existing case; namespace packages merge path entries) resolves
        # to the REAL module — every verdict below would silently measure real code.
        shadowed = [
            f"{t} imported from {f}"
            for t, f in sorted((payload.get("origins") or {}).items())
            if not Path(f).resolve().is_relative_to(stub_dir)
        ]
        if shadowed:
            print("check_stub: stub was shadowed by real code — verdicts void; the run "
                  "measured the real implementation, not the null stub:\n  "
                  + "\n  ".join(shadowed), file=sys.stderr)
            return 2
    except subprocess.TimeoutExpired:
        print("check_stub: pytest timed out after 600s against the stub", file=sys.stderr)
        return 2
    except json.JSONDecodeError as e:
        print(f"check_stub: could not run — the report is not valid JSON ({e}); the "
              f"pytest run under `{python}` broke mid-write.", file=sys.stderr)
        return 2
    except OSError as e:
        # A missing or broken interpreter is "could not look" (exit 2), never a
        # traceback — an uncaught traceback exits 1 and would read as findings.
        print(f"check_stub: could not run `{python} -m pytest` — {e}", file=sys.stderr)
        return 2
    finally:
        if keep:
            print(f"  [check_stub] stub kept at {stub_dir} — delete it; it is never committed.",
                  file=sys.stderr)
        else:
            shutil.rmtree(stub_dir, ignore_errors=True)

    recorded = _recorded_passes(suite_dir)
    findings: list[str] = []
    discriminated = 0
    for nodeid, r in sorted(results.items()):
        outcome, msg = r.get("outcome"), r.get("message", "")
        test = nodeid.split("::")[-1]
        if outcome == "failed" and (msg.startswith("AssertionError") or msg.startswith("Failed")):
            discriminated += 1
        elif outcome == "passed":
            # A parametrized nodeid ends in `[case]`; a recorded bare name covers every
            # case, and a recorded full id covers just its own.
            bare = test[: test.find("[")] if "[" in test and test.endswith("]") else test
            if test in recorded or bare in recorded:
                discriminated += 1  # an examined pass — recorded with its class in the graph
            else:
                findings.append(
                    f"NULLSTUB-PASS {nodeid}: green against a do-nothing target — binds nothing. "
                    f"Strengthen it, or record it with its class in handoff.nullstub_passes."
                )
        elif outcome == "failed":
            findings.append(
                f"NON-ASSERT {nodeid}: fails on `{msg}`, not its own assertion — it rides "
                f"machinery, so it may stay green when only the demand breaks."
            )
        elif outcome in ("skipped", "collection-skipped"):
            findings.append(f"SKIPPED {nodeid}: a skipped test discriminates nothing at spec time.")
        else:
            findings.append(
                f"BROKEN {nodeid}: {outcome} (`{msg}`) — proves the file is broken, not that "
                f"the test discriminates."
            )
    for f in findings:
        print(f"  {f}")
    print(f"\n[check_stub] {discriminated} discriminating, {len(findings)} finding(s), "
          f"targets: {sorted(targets)}.")
    return 1 if findings else 0


def main(argv: list[str]) -> int:
    _cli.utf8_stdio()
    opts, args = _cli.parse_argv(
        argv, valued={"--config", "--python"}, multi={"--target"}, flags={"--keep"}
    )
    # A `--python` with no value falls back to the default, never to None.
    python = opts["python"] or os.environ.get("SPEC_GRAPH_TEST_PYTHON", "python3")
    explicit: list[str] = opts["target"]
    keep = opts["keep"]
    cfg = _config.load(opts["config"])
    if args:
        # Absolute BEFORE use: run() moves cwd to the pytest rootdir, so a relative
        # suite/graph arg handed to pytest would resolve against the wrong base
        # (run from repo/tests with arg `spec`, pytest would hunt <rootdir>/spec).
        p = Path(args[0]).resolve()
        suite_dir = p if p.is_dir() else p.parent
    else:
        dirs = sorted({g.parent for g in _config.artifacts(cfg)})
        if len(dirs) != 1:
            print(f"check_stub: give the suite dir or graph explicitly (found {len(dirs)} "
                  f"candidate dirs)", file=sys.stderr)
            return 2
        suite_dir = dirs[0].resolve()
    root = _config.repo_root(suite_dir)
    targets, floor = _suite.target_modules(suite_dir, root)
    for t in explicit:
        targets.setdefault(t, set())
    for note in floor:
        print(f"  WARN [check_stub] {note}", file=sys.stderr)
    if not targets:
        print(
            f"check_stub: no target identified for {suite_dir} — every suite import resolves. "
            f"Name the modify-case target with --target <dotted.module>.",
            file=sys.stderr,
        )
        return 2
    return run(suite_dir, targets, python, keep)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
