"""Adapter contract for security system CLIs.

This ABC defines the interface that `/connect` generates and that the
investigation loop depends on. Implementations are standalone CLI scripts
under `scripts/tools/{system}_cli.py` — not imported as modules. This ABC
exists for documentation and contract-compliance testing, not runtime
dispatch.

CLI scripts implement this interface through argparse subcommands:

    python3 scripts/tools/{system}_cli.py health-check
    python3 scripts/tools/{system}_cli.py query <native_query> [--start ISO] [--end ISO] [--limit N] [--raw] [--run-dir DIR]

See `docs/design-v3-init-and-connect.md` for the full rationale, especially
§3 "Adapter Contract" and §3 "What the contract deliberately excludes".

Note: the existing `scripts/siem/wazuh_cli.py` predates this contract and
uses a flag-based interface (`--health-check`, `--query`) rather than
argparse subcommands. New adapters generated by `/connect` use
subcommands. The wazuh_cli.py migration is tracked separately.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class HealthResult:
    """Binary health check result.

    connected: did we reach the system and authenticate?
    error:     if not connected, what went wrong (connection refused,
               auth failed, timeout)? Human-readable, one line.
    detail:    optional structured extras for debugging (component
               statuses, version strings). Not required for pass/fail.
    """

    connected: bool
    error: str | None = None
    detail: dict[str, Any] = field(default_factory=dict)


@dataclass
class QueryResult:
    """Result of a native query execution.

    raw:          the system's response, minimally processed. JSON-serializable.
                  No field renaming, no schema normalization. The agent and
                  post-processing Python handle interpretation.
    total_hits:   how many results matched (before any limit). None if the
                  system doesn't report this.
    truncated:    True if results were cut off by a limit. The agent needs
                  to know when it's seeing a partial picture.
    query_echo:   the exact query that was executed (for audit and debugging).
    """

    raw: list[dict[str, Any]]
    total_hits: int | None = None
    truncated: bool = False
    query_echo: str = ""


class AdapterContract(ABC):
    """Interface that every system adapter implements.

    Two operations. Health check tells you if the system is reachable.
    Query executes a native query and returns results. Everything else —
    field enumeration, aggregation, post-processing — the agent does in
    Python after getting raw results.

    The contract is deliberately minimal. Capabilities like field
    enumeration, aggregation, schema normalization, and data freshness
    are excluded because they're either unbounded problems, query-language
    specific, or context-dependent. See the design doc for the reasoning.
    """

    @abstractmethod
    def health_check(self) -> HealthResult:
        """Binary connectivity check.

        Tests: can we reach the endpoint and authenticate?
        Does NOT assess data freshness, index health, or pipeline status.
        Those are unbounded problems — the investigation methodology handles
        them (e.g., checking if zero results means "clean" or "broken").

        CLI exit codes:
            0 — connected
            1 — connection or auth failure (print error to stderr)
        """
        ...

    @abstractmethod
    def query(
        self,
        native_query: str,
        time_start: str | None = None,
        time_end: str | None = None,
        limit: int = 500,
    ) -> QueryResult:
        """Execute a query in the system's native language.

        native_query: the query string as the system understands it.
            Splunk adapter receives SPL. Wazuh adapter receives Lucene.
            Elastic adapter receives KQL. No translation layer.

        time_start / time_end: ISO 8601 UTC. Optional — some systems don't
            support time-bounded queries (e.g., asset databases). Adapters
            that don't use time ranges ignore these parameters.

        limit: max results to return. Adapter handles pagination internally
            and sets truncated=True if total_hits exceeds limit.

        CLI exit codes:
            0 — query executed (even if zero results)
            1 — query execution failed (print error to stderr)
            2 — connection/auth failure (print error to stderr)
        """
        ...


# ---------------------------------------------------------------------------
# Contract compliance: what `/connect` and preflight.py verify
# ---------------------------------------------------------------------------

#: Required argparse subcommands every generated adapter must expose.
REQUIRED_SUBCOMMANDS = ("health-check", "query")

#: Required flags the `query` subcommand must accept. `--run-dir` is required
#: so the adapter can wrap output in salted untrusted-data delimiters when
#: invoked inside an investigation run.
REQUIRED_QUERY_FLAGS = ("--start", "--end", "--limit", "--raw", "--run-dir")

#: Environment knowledge `/connect` scaffolds for every newly-connected
#: system. Preflight does not hard-require every filename (the env layout
#: is flexible — data sources may be organized by data type rather than
#: per-system). These are the defaults `/connect` writes when it has
#: nothing else to go on.
SCAFFOLDED_KNOWLEDGE_ARTIFACTS = (
    "knowledge/environment/systems/{system}/config.env.template",
    "knowledge/environment/systems/{system}/field-notes.md",
    "knowledge/environment/data-sources/{system}.md",
)
