#!/usr/bin/env python3
"""Stub asset/identity connector — reference LookupContract implementation.

Returns asset records (CMDB-shape) and identity records (IdP-shape) from a
local JSON fixture. Used by the contextualize-leads (`endpoint-context`,
`identity-context`) at CONTEXTUALIZE time to enrich prologue vertices with
authoritative entity records, without taxing CONTEXTUALIZE on a real CMDB.

This is the canonical example of a LookupContract-shaped adapter. Real
production connectors (servicenow_assets_cli.py, okta_users_cli.py, ...) are
generated by /connect by copying this stub's structure and swapping in real
HTTP calls to a CMDB / IdP / asset DB.

Data source:
    JSON file at the path given by `SOC_AGENT_ASSET_DATA_PATH`. Schema:
        {
          "ips":   { "<ip>":   { ...record... }, ... },
          "users": { "<user>": { ...record... }, ... },
          "hosts": { "<host>": { ...record... }, ... }
        }

    Missing top-level keys are treated as empty dicts. Records are returned
    verbatim — no schema normalization.

Usage:
    python3 stub_asset_cli.py health-check
    python3 stub_asset_cli.py lookup ip 172.22.0.10 [--raw] [--run-dir DIR]
    python3 stub_asset_cli.py lookup user nagios
    python3 stub_asset_cli.py lookup host target-endpoint

Exit codes:
    0 — lookup executed (found OR not found, both valid per LookupContract)
    1 — lookup failed (unknown key_field, malformed data file)
    2 — connection / auth failure (never raised by the stub — documented for
        real vendor clones)
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


SUPPORTED_KEY_FIELDS = ("ip", "user", "host")
DATA_PATH_ENV = "SOC_AGENT_ASSET_DATA_PATH"


def _load_data() -> dict:
    """Load the JSON data file pointed to by SOC_AGENT_ASSET_DATA_PATH.

    Fails fast (RuntimeError) only when invoked — health-check and lookup
    both call this. Callers that never invoke a subcommand never trigger
    the env-var check, which is what lets unmigrated signatures avoid
    needing the var set.
    """
    val = os.environ.get(DATA_PATH_ENV)
    if not val:
        raise RuntimeError(
            f"{DATA_PATH_ENV} is not set. Point it at a JSON file with the "
            "{ips, users, hosts} schema."
        )
    path = Path(val)
    if not path.exists():
        raise RuntimeError(f"{DATA_PATH_ENV}={val} does not exist")
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"{DATA_PATH_ENV}={val} did not parse as JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise RuntimeError(f"{DATA_PATH_ENV}={val} root must be a JSON object")
    return data


# ---------------------------------------------------------------------------
# health-check
# ---------------------------------------------------------------------------


def cmd_health_check(_args: argparse.Namespace) -> int:
    """Confirm the data file loads cleanly. Real vendor clones would probe
    the upstream's auth endpoint instead.
    """
    try:
        data = _load_data()
    except RuntimeError as exc:
        payload = {"connected": False, "error": str(exc)}
        print(json.dumps(payload))
        return 1
    detail = {
        "stub": True,
        "data_path": os.environ.get(DATA_PATH_ENV, ""),
        "ips": len(data.get("ips") or {}),
        "users": len(data.get("users") or {}),
        "hosts": len(data.get("hosts") or {}),
    }
    print(json.dumps({"connected": True, "detail": detail}))
    return 0


# ---------------------------------------------------------------------------
# lookup
# ---------------------------------------------------------------------------


_BUCKET_BY_KEY_FIELD = {"ip": "ips", "user": "users", "host": "hosts"}


def _build_lookup_result(
    key_field: str, key_value: str, record: dict | None,
) -> dict:
    return {
        "found": record is not None,
        "record": record,
        "key_field": key_field,
        "key_value": key_value,
        "error": None,
    }


def cmd_lookup(args: argparse.Namespace) -> int:
    """Resolve a single key → record. Not-found is a valid result, exit 0.

    Lookup never short-circuits — even when the upstream returns nothing,
    that's evidence the agent uses (an unknown source IP says different
    things than a known one).
    """
    key_field = args.key_field
    if key_field not in SUPPORTED_KEY_FIELDS:
        print(
            f"error: unsupported key_field {key_field!r} "
            f"(supported: {', '.join(SUPPORTED_KEY_FIELDS)})",
            file=sys.stderr,
        )
        return 1

    try:
        data = _load_data()
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    bucket = data.get(_BUCKET_BY_KEY_FIELD[key_field]) or {}
    if not isinstance(bucket, dict):
        print(
            f"error: data file's `{_BUCKET_BY_KEY_FIELD[key_field]}` "
            "key must be a JSON object",
            file=sys.stderr,
        )
        return 1
    record = bucket.get(args.key_value)
    if record is not None and not isinstance(record, dict):
        print(
            f"error: data file's `{_BUCKET_BY_KEY_FIELD[key_field]}.{args.key_value}` "
            "must be a JSON object",
            file=sys.stderr,
        )
        return 1

    print(json.dumps(_build_lookup_result(key_field, args.key_value, record)))
    return 0


# ---------------------------------------------------------------------------
# CLI wiring
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Stub asset/identity connector — reference LookupContract CLI",
    )
    sub = p.add_subparsers(dest="subcommand", required=True)

    sub.add_parser(
        "health-check",
        help="Verify the data file loads, then exit",
    )

    lk = sub.add_parser(
        "lookup",
        help="Fetch a single record by key",
    )
    lk.add_argument(
        "key_field",
        choices=SUPPORTED_KEY_FIELDS,
        help="Which bucket to look in",
    )
    lk.add_argument("key_value", help="The key to resolve")
    lk.add_argument(
        "--raw",
        action="store_true",
        help="Reserved for upstream-passthrough adapters; ignored by the stub",
    )
    lk.add_argument(
        "--run-dir",
        default=None,
        help="Investigation run directory (reserved for salted-delimiter wrapping; "
             "the stub does not wrap, but the flag is documented for contract compliance)",
    )

    return p


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if args.subcommand == "health-check":
        return cmd_health_check(args)
    if args.subcommand == "lookup":
        return cmd_lookup(args)

    parser.error(f"unknown subcommand: {args.subcommand}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
