#!/usr/bin/env python3
"""Stub ticketing connector — reference ActionContract implementation.

This is the canonical example of a ticketing-family action adapter. The base
ActionContract (schemas/adapter_contract.py) is deliberately thin — only
health_check is abstract — so the authoritative shape for the ticketing
family (close subcommand, required flags, dry-run-first behavior, response
format) lives here. New vendor connectors (jira_cli.py, servicenow_cli.py,
thehive_cli.py, ...) are generated by /connect by copying this stub's
structure and swapping in real HTTP calls.

Used by:
    - close_ticket_action.py unit tests (real subprocess dispatch)
    - developers hand-testing the Stop handler before connecting a real vendor
    - /connect Phase 2 as a template
    - preflight.py action-adapter probe

One ticket per invocation. Batch closing is not supported — the ActionContract
is designed for single-target dispatch (the Stop-stage hook dispatches one call
per investigation run, which corresponds to exactly one ticket). Callers that
need to close multiple tickets must invoke the CLI once per ticket.

Usage:
    python3 stub_ticket_cli.py health-check
    python3 stub_ticket_cli.py close --ticket-id SEC-1 \\
        --reason "benign-burst (monitoring-probe)" \\
        --author "soc-agent v3.4.0" \\
        --documentation "Investigation: run-abc; archetype: monitoring-probe" \\
        [--run-dir runs/run-abc] [--dry-run|--execute]

Exit codes:
    0 — success (including dry-run)
    1 — usage / contract error (missing flag, etc.)
    2 — connection / auth failure (never raised by the stub — documented for
        real vendor clones)
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SOC_AGENT_DIR = Path(os.environ.get("SOC_AGENT_DIR", SCRIPT_DIR.parent.parent))

# Non-secret config would live here for a real vendor connector. The stub
# doesn't need it, but the pattern is documented as a commented block so
# the file works as a template.
#
# CONFIG_PATH = (
#     SOC_AGENT_DIR
#     / "knowledge"
#     / "environment"
#     / "systems"
#     / "stub-ticket"
#     / "config.env"
# )
# REQUIRED_CONFIG_KEYS = ["STUB_TICKET_BASE_URL"]
# Required env vars (secrets, never in config.env): STUB_TICKET_TOKEN


STUB_LOG_NAME = "stub_ticket_actions.jsonl"


def _runs_dir() -> Path:
    return Path(os.environ.get("SOC_AGENT_RUNS_DIR", str(SOC_AGENT_DIR / "runs")))


# ---------------------------------------------------------------------------
# health-check
# ---------------------------------------------------------------------------


def cmd_health_check(_args: argparse.Namespace) -> int:
    """Always-green health check for the stub.

    Real vendor clones would probe the ticketing API's ping/auth endpoint
    and return a HealthResult JSON with connected=false + error on failure.
    """
    payload = {
        "connected": True,
        "detail": {"stub": True, "note": "stub_ticket_cli has no upstream"},
    }
    print(json.dumps(payload))
    return 0


# ---------------------------------------------------------------------------
# close
# ---------------------------------------------------------------------------


def _build_action_result(
    ticket_id: str,
    reason: str,
    author: str,
    documentation: str,
    dry_run: bool,
) -> dict:
    """Construct the ActionResult dict the stub returns on stdout."""
    return {
        "action": "close_ticket",
        "target": ticket_id,
        "dry_run": dry_run,
        "success": True,
        "error": None,
        "detail": {
            "reason": reason,
            "author": author,
            "documentation": documentation,
            "stub": True,
        },
    }


def cmd_close(args: argparse.Namespace) -> int:
    """Close (or dry-run close) a ticket.

    Dry-run is the default. --execute must be passed explicitly to write.
    The stub has no upstream, so --execute just appends a row to
    runs/stub_ticket_actions.jsonl for audit visibility.

    Dry-run short-circuits *before* any lookup, per the contract. This is
    what makes the preflight probe (`close --ticket-id PROBE-0 --dry-run`)
    safe regardless of whether PROBE-0 exists.
    """
    # Contract check: --dry-run and --execute are mutually exclusive.
    if args.dry_run and args.execute:
        print(
            "error: --dry-run and --execute are mutually exclusive",
            file=sys.stderr,
        )
        return 1

    # Dry-run is the default. Anything that isn't explicit --execute is dry-run.
    dry_run = not args.execute

    result = _build_action_result(
        ticket_id=args.ticket_id,
        reason=args.reason,
        author=args.author,
        documentation=args.documentation,
        dry_run=dry_run,
    )

    if not dry_run:
        runs_dir = _runs_dir()
        runs_dir.mkdir(parents=True, exist_ok=True)
        log_path = runs_dir / STUB_LOG_NAME
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "run_dir": args.run_dir,
            **result,
        }
        with open(log_path, "a") as f:
            f.write(json.dumps(entry) + "\n")

    print(json.dumps(result))
    return 0


# ---------------------------------------------------------------------------
# CLI wiring
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Stub ticketing connector — reference ActionContract CLI",
    )
    sub = p.add_subparsers(dest="subcommand", required=True)

    sub.add_parser(
        "health-check",
        help="Verify connectivity to the ticketing system, then exit",
    )

    c = sub.add_parser(
        "close",
        help="Close a ticket. Defaults to --dry-run; --execute writes.",
    )
    c.add_argument(
        "--ticket-id",
        required=True,
        help="Single ticket identifier to close (one per invocation; batch not supported)",
    )
    c.add_argument("--reason", required=True, help="One-line close reason")
    c.add_argument("--author", required=True, help="Author string (e.g. soc-agent v3.4.0)")
    c.add_argument(
        "--documentation",
        required=True,
        help="Free-form close documentation (run dir + archetype citation)",
    )
    c.add_argument(
        "--run-dir",
        default=None,
        help="Investigation run directory (reads salt from meta.json if wrapping output)",
    )

    mode = c.add_mutually_exclusive_group()
    mode.add_argument(
        "--dry-run",
        action="store_true",
        help="Default. Describe what WOULD happen without writing.",
    )
    mode.add_argument(
        "--execute",
        action="store_true",
        help="Actually close the ticket. Only passed by the Stop-stage hook.",
    )

    return p


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if args.subcommand == "health-check":
        return cmd_health_check(args)
    if args.subcommand == "close":
        return cmd_close(args)

    parser.error(f"unknown subcommand: {args.subcommand}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
